### DISCUSSION TITLE
Svelte 5 and Tailwind CSS 4

### DISCUSSION THREAD

**Discussion by dilrajsachdev** [themesberg/flowbite-svelte#1529] [General]
Hi, 
Just wondering, if there is any plans for upgrading to Svelte 5 and Tailwind 4 ?
I can try to contribute on this , if possible
Thanks,
Dilraj

**Comment by sbscan** [comment]
indeed many components working with Svelte 5 runes mode and Tailwind 4.

**Comment by therealsujitk** [comment]
This the css file that worked for me to configure tailwind 4 and flowbite-svelte.

```css
/* Write your global styles here, in PostCSS syntax */
@import 'tailwindcss';
@source "../node_modules/flowbite-svelte";
@plugin 'flowbite/plugin';

@custom-variant dark (&:where(.dark, .dark *));

@theme {
  --color-primary-50: #fff5f2;
  --color-primary-100: #fff1ee;
  --color-primary-200: #ffe4de;
  --color-primary-300: #ffd5cc;
  --color-primary-400: #ffbcad;
  --color-primary-500: #fe795d;
  --color-primary-600: #ef562f;
  --color-primary-700: #eb4f27;
  --color-primary-800: #cc4522;
  --color-primary-900: #a5371b;
}

@layer base {
  button:not(:disabled),
  [role='button']:not(:disabled) {
    cursor: pointer;
  }
}
```
